### ISSUE TITLE
Missing support for belongs to many relationships

### ISSUE THREAD

**Issue by TonnyORG** [optimistdigital/nova-sortable#100]
I was just testing your package within an app and I find out that it does work on `hasMany` and `belongsTo` (this is not documented but `'sort_on_belongs_to' => true` does the trick) relationships but it doesn't for `belongsToMany`, is it possible to add such support? What do you think?

**Comment by KasparRosin** [comment]
Support for ManyToMany already exist.

Here is the documentation for this: https://github.com/optimistdigital/nova-sortable/blob/master/docs/sorting/many-to-many.md
