### ISSUE TITLE
Sort order not working correctly

### ISSUE THREAD

**Issue by Mazeland** [optimistdigital/nova-sortable#102]
Hi,

The package seems to have a bug. I've made 2 related models with a manyToMany relation.
1. stockphoto (750 items)
2. stockphoto_category (21 items)

I can upload photos and can add a category to them via Nova. When I try to sort rows with drag and drop in the detail view with a small amount of rows to sort (e.g. 30) everything works fine. But now I have 350 rows to sort and things get messed up. I use the option 'move to end' to sort the rows and suddenly some other rows are unexpected changing order by itself. The column sort_order in the database is also getting double id's.

<img width="669" alt="Screenshot 2021-09-01 at 17 11 37" src="https://user-images.githubusercontent.com/13019926/131696965-4c42ddc2-203e-4f38-8474-b86a127ddbf3.png">

I've set $perPageViaRelationship to 100. The list view in Nova has thumbnails which are automatically generated after uploading the image. 

<img width="1250" alt="Screenshot 2021-09-01 at 17 20 08" src="https://user-images.githubusercontent.com/13019926/131698317-ab7f6381-5d4b-45be-91a1-2e9bd81b4663.png">

Can someone help with this issue? If some information is missing, please let me know. 

Regards, 
Ruud

**Comment by Tarpsvo** [comment]
That's really weird, I am unable to reproduce this issue on my testing setup.

Here's my setup. Two models: Artist and Track. A Track can have many Artists (many-to-many).

```php
// Artist model

class Artist extends Model
{
    public function tracks()
    {
        return $this->belongsToMany(Track::class)
            ->using(ArtistTrack::class)
            ->withPivot('id', 'pivot_sort_order');
    }
}
```

```php
// ArtistTrack pivot

class ArtistTrack extends Pivot implements Sortable
{
    use SortableTrait;

    public $primaryKey = 'id';
    public $incrementing = true;
    public $timestamps = false;

    public $sortable = [
        'order_column_name' => 'pivot_sort_order',
        'sort_when_creating' => true,
    ];

    public function buildSortQuery()
    {
        return static::query()
            ->where('track_id', $this->track_id); // As we're sorting Artists belonging to a Track, we're setting this to filter using track_id
    }
}
```

```php
// Track model

class Track extends Model
{
    public function artists()
    {
        return $this->belongsToMany(Artist::class)
            ->using(ArtistTrack::class)
            ->withPivot('id', 'pivot_sort_order');
    }
}
```

I don't know what the difference is, but it seems to work for me. :S
