### ISSUE TITLE
Sort order of Resource is reversed when HasSortableManyToManyRows is used

### ISSUE THREAD

**Issue by AforDesign** [optimistdigital/nova-sortable#104]
Laravel Version: 7.30.4
Nova Version: 3.29.0
PHP Version: 7.4.16
optimistdigital/nova-sortable: 1.6.2

**Description (updated):**

Using the HasSortableManyToManyRows trait affects the order of the resource's own indexpage.
It sets the order to: **ID, DESC**

This behaviour overrules any sorting preference as set in the Resource
Turning it off shows index in correct order.

To be clear; the trait affects the index page of the resource itself.
The order of the resource in it's many-to-many relation works fine

**Comment by Tarpsvo** [comment]
Hi! That is intentional. If you want to sort on both ManyToMany AND index views, please refer to this issue: https://github.com/optimistdigital/nova-sortable/issues/60
