### ISSUE TITLE
Project overwrite of ResourceTableRow and ResourceTable are taking precedence over nova-sortable ones

### ISSUE THREAD

**Issue by msouto346** [optimistdigital/nova-sortable#106]
Hello, as the title describes, I have my own overwrites of those 2 components which is causing the package to not work for me anymore after adding them. Is there a "simple" way to overcome this or am I forced to try and replicate the package functionality?

I know this is not a bug of the package but decided to open the issue in case someone has came into contact with this situation before.

**Comment by Tarpsvo** [comment]
Hi! That's a tough one, if you've overwritten the table and row components then there's no easy way to ensure this package will work.

We have a compatibility guide for nova-resizable and nova-sortable here: https://github.com/optimistdigital/nova-resizable/discussions/2

But this doesn't really apply to your usecase. I think you have to manually replicate the JS functionality by copy/pasting it from this project sadly.
