### ISSUE TITLE
Docs addition

### ISSUE THREAD

**Issue by jacob418** [optimistdigital/nova-sortable#109]
In my project i needed to use the `indexQuery` method myself leading - obviously - to broken sorting behavior. I came up with the following solution which is probably worth mentioning in the docs:

```php
    public static function indexQuery(NovaRequest $request, $query)
    {
        $query->withCount(['children', 'descendants', 'modules']);

        return parent::indexQuery($request, HasSortableRows::indexQuery($request, $query));
    }
```

Another way to do this with an alias is proposed here: https://stackoverflow.com/questions/11939166/how-to-override-trait-function-and-call-it-from-the-overridden-function/11939306#11939306

**Comment by Tarpsvo** [comment]
Hi @jacob418! Thanks for the tip. :) I added it to the README.md.

**Comment by pepijn-vanvlaanderen** [comment]
@jacob418 / @Tarpsvo this actually did not work for me, maybe this has been updated in the Nova package but the parent indexQuery adds sorting:
```
    /**
     * Build an "index" query for the given resource.
     *
     * @param  NovaRequest  $request
     * @param  Builder  $query
     * @return Builder
     */
    public static function indexQuery(NovaRequest $request, $query)
    {
        if (empty($request->get('orderBy'))) {
            $query->getQuery()->orders = [];

            return $query->orderBy(key(static::$indexDefaultOrder), reset(static::$indexDefaultOrder));
        }

        return $query;
    }
```
That results in the sorting from `HasSortableRows::indexQuery` will be overwriten. I think the docs should be updated to just use:
```
    public static function indexQuery(NovaRequest $request, $query)
    {
        $query->withCount(['children', 'descendants', 'modules']);

        return HasSortableRows::indexQuery($request, $query);
    }
```

**Comment by jacob418** [comment]
@pepijn-vanvlaanderen wich version of Nova are you using? Is it still 3? Do you have a package installed that adds default sorting functionality? Im asking this because in Nova 3 default sorting was not possible out of the box.

Anyway, I'd consider your second example a possible solution for your problem. Another approach is Is to overwrite this in your base resource class: Use the [`class_uses_recursive`](https://laravel.com/docs/8.x/helpers#method-class-uses-recursive) helper of Laravel 8 to detect if the trait in question (in this case `HasSortableRows`) gets used by the current instance, if yes, skip the default order.
