### ISSUE TITLE
BelongsToMany Pivot Table Ordering

### ISSUE THREAD

**Issue by mdavis1982** [optimistdigital/nova-sortable#20]
I've read the docs, and tried the example [here](https://github.com/optimistdigital/nova-sortable/blob/master/docs/sorting/belongs-to.md), but I can't get ordering via a column on a Pivot table to work.

I have a `tracks` table, and an `artists` table, and they are linked with an `artist_tracks` table. I've added the `sort_order` column to the `artist_tracks` table, but no matter what I try, I can't get the draggable sorting behaviour to work in Nova (v.3.4.0) at all.

Is this possible? And if so, could you possibly tell me how to make this work please? 😄 

Thanks

**Comment by Tarpsvo** [comment]
Did you add the sorting to the pivot model query on the Artists model?

```
public function tracks()
{
  return $this->belongsToMany(Track::class, 'artist_tracks')
    ->orderBy('artist_tracks.sort_order'); // This thing
}
```

**Comment by mdavis1982** [comment]
@Tarpsvo I did... The actual ordering is working, but I couldn't attach a new Artist to a track (because it said that `sort_order` didn't have a default value), and I can't get the draggable UI to appear.

When I'm on my `Track` detail page, I want to be able to reorder the `Artists` that are attached to the `Track`.

**Comment by Tarpsvo** [comment]
Hey! When adding HasMany support, I did indeed break BelongsToMany. I made some fixes and managed to get a new project with Artist/Track models working.

Here's some of the code:

```php
class Track extends Model
{
    public function artists()
    {
        return $this->belongsToMany(Artist::class)
            ->orderBy('artist_track.sort_order');
    }
}
```

```php
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;

class Artist extends Model implements Sortable
{
    use SortableTrait;

    public $sortable = [
        'order_column_name' => 'sort_order',
        'sort_when_creating' => false,
        'sort_on_belongs_to' => true,
    ];

    public function tracks()
    {
        return $this->belongsToMany(Track::class);
    }
}
```

```php
// Track.php Resource
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Name'),
            BelongsToMany::make('Artists', 'artists'),
        ];
    }
```

```php
// Artist.php Resource

class Artist extends Resource
{
    use HasSortableRows;

...
}
```

The set up is indeed pretty difficult and prone to breaking at this stage, I'll look into what I can do to simplify the setup. Try setting it up again with 1.4.1 and let me know if this works now. Good luck!

**Comment by mdavis1982** [comment]
@Tarpsvo Thanks for taking a look at this 😄 

This mostly works now, aside from one thing. When attaching an `Artist` to a `Track` using Nova, the `sort_order` field on the pivot table isn't filled correctly.

I thought this might be because `sort_when_creating` was `false`, but changing it to `true` doesn't fill the `sort_order` column either.

How would I go about ensuring that the column is filled when attaching an `Artist` to a `Track`?

Also, how would I go about changing the name of the `sort_order` column?

Thanks again for this - I really appreciate it. 😄

**Comment by authanram** [comment]
I can confirm what @Tarpsvo is reporting regarding the sort_order column on the pivot table.

1. Exception if there is no `sort_order` column on the main table. in my case i only want to sort on pivot only, not main table. So a `sort_order` column is not required on the main table.

2. Sortings are applied to main table when sorting on the pivot index view.

I've fixed the sorting on pivot for the drag 'n drop here; https://github.com/authanram/nova-sortable/commit/e1dab7f938e6b2e453aa22c82d404b879a580b8f

If i would have more time, i would test it properly and apply a pull request, but i don't have. Maybe my quick workaround can help to  get into more quick.

**Comment by Tarpsvo** [comment]
Alright, reworked it a bit and it works on my machine™.  Check out the new docs at [sorting/many-to-many.md](https://github.com/optimistdigital/nova-sortable/blob/master/docs/sorting/many-to-many.md) and let me know if the solution works now. Should now be more logical and require less setup, even though the user is required to create a Pivot model for the relationship.

**Comment by mdavis1982** [comment]
@Tarpsvo Thanks so much for taking the time to look at this again.

I've just tried this out, and it is now filling in the `sort_order` field on the pivot table 😄 

I have noticed, however, that it doesn't seem to be taking into account both of the columns on the pivot table any more.

So, if I have the following:

| artist_id | track_id | sort_order |
| --------- | -------- | ---------- |
| 1         | 1        | 1          |
| 2         | 1        | 2          |

If I then attach the `artist` with an `id` of `1` to another track, I get the following:

| artist_id | track_id | sort_order |
| --------- | -------- | ---------- |
| 1         | 1        | 1          |
| 2         | 1        | 2          |
| 1         | 2        | 3          |

The `sort_order` should be reset to `1` for this attachment, I think?

Also, I noticed that the `sort_order` column now starts at `1` whereas before it was starting at `0`.

Again, thanks for looking at this... I really appreciate it 😄

**Comment by mdavis1982** [comment]
@Tarpsvo Okay... I've just fixed this for my use-case.

I needed to add a `buildSortQuery()` method to the `ArtistTrack` pivot model like so:

```php
public function buildSortQuery()
{
    return static::query()
        ->where('artist_id', $this->artist_id)
        ->where('track_id', $this->track_id);
}
```

Do you think it's worth adding this to the docs? 😄

**Comment by mdavis1982** [comment]
@Tarpsvo Okay, scratch that... Constraining to both columns doesn't work.

Instead, I needed to just constrain to a single column:

```php
public function buildSortQuery()
{
    return static::query()
        ->where('track_id', $this->track_id);
}
```

I am still having the issue where the initial attach is getting an order of `1` and not `0` though.

**Comment by mdavis1982** [comment]
@Tarpsvo Sorry - I've also just noticed that the Move to Start and Move to End buttons don't work, because they're trying to call the methods on the `Artist` model, and not on the pivot model.

**Comment by Tarpsvo** [comment]
Pretty sure I got it working now, but that required a lot of new changes. Biggest of which is the new requirement of having a primary key column `id` on the pivot table. I'm on the verge of thinking of removing support entirely due to its complexity. Sorting stuff on pivot tables is a nightmare. You sure you can't use HasMany on your track/artist relationships? :D

**Comment by mdavis1982** [comment]
@Tarpsvo Thanks for your work on this 😄 

Please don't remove support - I definitely need this functionality 😁 This is the only Nova package with a decent user interface and UX that does all of this sorting functionality and the ecosystem would definitely be worse off without your work on this!

I'll take this for a spin today and let you know how I get on... I really do appreciate you jumping on these problems so quickly!

**Comment by mdavis1982** [comment]
@Tarpsvo Just had a play with this... There are a couple of things that aren't working for me.

If I have no artists attached to a track, I get an error about trying to access `->pivot` on a `null` object. I think this can be fixed in `HasSortableRows` on line 25 by wrapping in `optional()` but I'm not sure what knock on effects that would have.

Also, the `Move to Start` and `Move to End` buttons only work if the order column name hasn't been changed from `sort_order`. In my case, I've renamed it to `order` and set `'order_column_name' => 'order',` in my pivot model.

I believe this is hard-coded on line 23 of the `HasSortableRows` trait.

Apart from those two things, this works as expected. If you could fix those two errors, I'd be eternally grateful!

Thanks 😄

**Comment by Tarpsvo** [comment]
Hey again! Fixed the two mentioned errors and it should be good in version 1.4.4. Thanks for helping me test this!

**Comment by mdavis1982** [comment]
@Tarpsvo Thank you so much! This all seems to be working now! 😄

**Comment by Tarpsvo** [comment]
Nice! Let me know if anything breaks again. :D Good luck!

**Comment by Jon78** [comment]
Hi there. We're trying to add sorting functionality to an existing pivot table and could use some help. After adding the `sort_order` column, what do we set the values to? Also [this working example](https://github.com/optimistdigital/nova-sortable/issues/20#issuecomment-616644150) seems to differ from the [docs](https://github.com/optimistdigital/nova-sortable/blob/master/docs/sorting/many-to-many.md). Do we use the HasSortableRows-trait from the example or the HasSortableManyToManyRows-trait from the docs? And should the $sortable-public contain `'sort_on_belongs_to' => true,` or not? Thanks for clarifying!

**Comment by Tarpsvo** [comment]
The solution was reworked since this example was posted here, so the docs are more up to date and should be correct.

The new `sort_order` column should basically be set to the ID of the column.

`sort_on_belongs_to` no longer exists, instead it uses the HasSortableManyToManyRows trait.

Hope this helps!

**Comment by Jon78** [comment]
Thanks, I can now order existing items by dragging them. Or at least the `sort_order` values in the database are updated. After reloading a page however the items are once again ordered by ID, so a user might think nothing has changed. Also attaching new resources or using the 'move to front/back' buttons reloads the relationship and (visually) orders the resources by ID.

Is there a fix/workaround for this? Or could we at least show the `sort_order` value on the relationship index in Nova?

I know that ordering relations in Nova is notoriously hard, let alone ordering by pivot attributes, so this might be beyond the scope of this package 😀️
