### ISSUE TITLE
Not able to getting it to work

### ISSUE THREAD

**Issue by gerardnll** [optimistdigital/nova-sortable#24]
Hi,

I've followed all the instructions and I'm not seeing the buttons to reorder the resources in the index page. I'm seeing the JS being loaded but nothing appears. I do not need to add order as a field right? I have the latest Nova and Laravel version.

Thanks.

**Comment by Tarpsvo** [comment]
Hi!

Do confirm your model has the `$sortable` attribute and `SortableTrait` and your Resource has `HasSortableRows` trait.

There's no field for this, it should work using the given traits.

**Comment by gerardnll** [comment]
Sure it does.

```
<?php

namespace App\Models;

use App\Models\Traits\Actionable;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;

final class Provider extends Base implements Sortable
{
    use Actionable;
    use SortableTrait;

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'order' => 'int'
    ];

    /**
     * @var array
     */
    public $sortable = [
        'order_column_name' => 'order',
        'sort_when_creating' => true,
    ];
...
```

```

<?php

namespace App\Nova;

use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Text;
use OptimistDigital\NovaSortable\Traits\HasSortableRows;

class Provider extends Resource
{
    use HasSortableRows;

    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\Models\Provider';

```

**Comment by gerardnll** [comment]
I see the JS being loaded and the setting sortable = true

![Captura de Pantalla 2020-04-28 a les 13 09 59](https://user-images.githubusercontent.com/2018022/80480816-9c8c0600-8951-11ea-8db3-baa589470fda.png)

**Comment by Tarpsvo** [comment]
Hmm, I wonder if there's any other packages you use that might be overwriting the `resource-table-row` component?

**Comment by Tarpsvo** [comment]
![image](https://user-images.githubusercontent.com/2018660/80481364-f2b17700-895a-11ea-9719-1ed9208b3501.png)

**Comment by gerardnll** [comment]
No, the results just show your package.

**Comment by gerardnll** [comment]
Ok, fixed. It has to do with permissions. Sorry.

**Comment by Tarpsvo** [comment]
Ah, yes, I just reached the same conclusion. If actions are not available and the user isn't allowed to delete anything, the checkboxes are not displayed, but currently the reorder component renders alongside the checkbox component. I'll get to fixing it in a second. Thanks!

**Comment by gerardnll** [comment]
Maybe it's a good idea to use the Field way, so we can use permissions/abilities, and also you avoid overwriting components (which is always kind of dangerous).

**Comment by Tarpsvo** [comment]
Sadly, I don't think it can be done with a field as the whole row has to be wrapped inside the draggable component for it to be draggable. I agree that overwriting components is dangerous as breaking changes could come at any time, but the only "field" way to do it would be to just add a button to move it up and down one slot and that seems a bit too tedious. Draggable seems to be the best UX solution here.

Meanwhile, I released version 1.4.6 with the fix for displaying the reorder component when there's no checkbox (due to permissions). Just update the package to 1.4.6 and you can put your original permissions back. Good luck!

**Comment by gerardnll** [comment]
It's weird because I cannot reorder even though I have the update permission. Does it only appear when the 'delete' permission is true?

**Comment by Tarpsvo** [comment]
Hmm, it should appear no matter what. Did you try force-refreshing? The nova-sortable JavaScript may be cached.

**Comment by gerardnll** [comment]
Yes, my bad. Thanks a lot.

**Comment by Tarpsvo** [comment]
Awesome!
