### ISSUE TITLE
Extend documentation hasMany

### ISSUE THREAD

**Issue by svenvanhees** [optimistdigital/nova-sortable#25]
Hi,

While reading the docs, you are stating this: 
> Sorting on HasMany relationship
> NB! The resource can only be sorted on either the Index view or the HasMany list view, but not both!
> 

How do we choose to use the sortable trait on the the HasMany list view instead of the index view?

**Comment by Tarpsvo** [comment]
The toggle is the `sort_on_has_many` key on the `$sortable` attribute.

```php
public $sortable = [
  'order_column_name' => 'sort_order',
  'sort_when_creating' => true,
  'sort_on_has_many' => true,
];
```

**Comment by svenvanhees** [comment]
My apologies for not explaining further. But the sort_on_has_many does not function correctly.

It only allows me to sort on the index page, and not on the hasmany relation page.
![image](https://user-images.githubusercontent.com/3237025/80502777-55ae0880-8971-11ea-842d-b9d7044b5d3a.png)

**Comment by Tarpsvo** [comment]
That's odd, it should work. It's exactly like the Post<->Comment relationship in the example.

**Comment by svenvanhees** [comment]
After reading the releases page, I saw that the HasMany support was added in the 1.4 release. I was still locked in on ˆ1.3. Any chance this could be mentioned in the docs?

Thanks anyways!
