### ISSUE TITLE
Icon's don't appear in HasMany relation

### ISSUE THREAD

**Issue by thomasdominic** [optimistdigital/nova-sortable#28]
Nova 3.5
Nova-sortable 1.4.7

I'm including `HasSortableRows` trait but icon to sort don't appear in listing.
I haven't php error and console error.
This feature was ok few month ago and I didn't modify the code, only update.
![Capture d’écran de 2020-04-30 16-22-15](https://user-images.githubusercontent.com/17202290/80721811-f54cd180-8afe-11ea-8fed-781ba71f67de.png)

I don't know how explain my issue....

**Comment by Tarpsvo** [comment]
You can only sort on **either** the index view or the HasMany relationship view. The toggle is the following:

```php
public $sortable = [
  'order_column_name' => 'sort_order',
  'sort_when_creating' => true,
  'sort_on_has_many' => true, // This
];
```

**Comment by thomasdominic** [comment]
Yes, I see it in https://github.com/optimistdigital/nova-sortable/issues/25

Thanks you very much for this packages :)
