### ISSUE TITLE
Is this package store order in Database 

### ISSUE THREAD

**Issue by HalaAlmomanii** [optimistdigital/nova-sortable#29]
Hello,
I would ask i install it and it was great but when i drop and drag row  the database column order not change 

Is this package just frontend ?

**Comment by cgarofalo** [comment]
@HalaAlmomanii You may have the same issue as I do: #31

**Comment by HalaAlmomanii** [comment]
@cgarofalo  well in nova i was having index query method in resource and i used the trait which also have indexqurey  method so it was override , and that was my problem

**Comment by Tarpsvo** [comment]
Ah yes, I should probably mention that somewhere in the docs. The HasSortableRows does override the indexQuery method and will not work without it.
