### ISSUE TITLE
400 error on update-order route

### ISSUE THREAD

**Issue by cgarofalo** [optimistdigital/nova-sortable#31]
I am getting  `An error occurred while trying to reorder the resource.` when I try to drag and drop reorder the rows. "Move to first" and "Move to end" work as expected.

When I check the console I have a `Failed to load resource: the server responded with a status of 400 (Bad Request)` On the `update-order` route.

Laravel : 6.18.15
Nova: 2.12
PHP: 7.3.1

**Comment by Tarpsvo** [comment]
Does the invalid request have a body? The SortableController's 400 responses should return an error message when anything fails.

**Comment by cgarofalo** [comment]
Hi,
The only response I can find is `resourceName: "invalid"`, but I don't see how my resource name is invalid.

**Comment by Tarpsvo** [comment]
Hmm, is your Resource properly registered?

```
$resourceClass = Nova::resourceForKey($viaResource);
if (empty($resourceClass)) return response()->json(['resourceName' => 'invalid'], 400);
```

Nova can't find it the resource for some reason.

**Comment by cgarofalo** [comment]
I have tried this on a vanilla install of Laravel 6+ and Nova 2+. It works. I'll have to see what's different about my project concerning resources. I'll post back if I find a solution, in case anyone else encounters the same issue.

**Comment by cgarofalo** [comment]
I figured it out. The update-order POST request was passing empty strings instead of null for ViaResource. The problem was I had the `\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class`middleware commented out in my project.

**Comment by Tarpsvo** [comment]
Glad you figured it out! I think I found out what caused it in the package as well and added a fix for that. The middleware should no longer be necessary in version 1.4.11.
