### ISSUE TITLE
Sortable doesn't work when delete policy resource enabled.

### ISSUE THREAD

**Issue by muhghazaliakbar** [optimistdigital/nova-sortable#32]
I'm trying to implement the package in my resource, but doesn't work because the delete policy method related to the resource is enabled.

**Comment by Tarpsvo** [comment]
What's the error?

**Comment by muhghazaliakbar** [comment]
There is no error, the sortable field not showing in the index resource page.

**Comment by Tarpsvo** [comment]
Hi! This is now fixed in version 2.1.0. :) Good luck!

**Comment by e-yakubov** [comment]
@Tarpsvo Hi! Its not working on 2.1.5 version:
<img width="1094" alt="Screenshot 2021-02-01 at 16 57 57" src="https://user-images.githubusercontent.com/5730844/106475582-c230d780-64ae-11eb-9db6-7209e9984504.png">

`public function authorizedToDelete(Request $request)
    {
        return false;
    }`
