### ISSUE TITLE
Change default order column name

### ISSUE THREAD

**Issue by shaffe-fr** [optimistdigital/nova-sortable#41]
Hello,
The default order column of this package is `sort_order` whereas spatie/eloquent-sortable uses `order_column`.
The same order column name would allow both packages to work without any configuration for simple use case.
As it would be a BC, would you be open to a PR to change the default order column name to "order_column"?
Thanks for your work,
Best,
Karel

**Comment by Tarpsvo** [comment]
Hi!

As the user has to create a migration anyway, it's not going to be zero configuration either way. To me, it seems weird to name a column as a `_column`, so I think I'll keep it as `sort_order` for now.

**Comment by shaffe-fr** [comment]
Hi,
I understand, I also think `_column` is weird. 
Thanks
