### ISSUE TITLE
Sortable only when viewing through relation

### ISSUE THREAD

**Issue by ZuggieTM** [optimistdigital/nova-sortable#44]
Is it possible to make a resource sortable ONLY when you view it through a relation, so disable sorting when you're viewing the resource index itself?

**Comment by Tarpsvo** [comment]
If it shows the sorting buttons on both Index view and the relationship view, then that's a bug. Let me look into it.

**Comment by ZuggieTM** [comment]
Ah alright. Yeah that's what's happening.

Also, I noticed that in the relationship view, it sorts my sortable relations by the primary key rather than the order key. This makes the sorting incorrect when dragging them around.

**Comment by Tarpsvo** [comment]
What type of a relationship is it? HasMany?

**Comment by ZuggieTM** [comment]
It's actually a MorphToMany / MorphedByMany.

I've set it up as explained in https://github.com/optimistdigital/nova-sortable/blob/master/docs/sorting/many-to-many.md

It works fine, the only issue is the sorting button showing on the resource itself and when viewing the resource in a relationship, it's sorted by primary ID rather than the column defined in 'order_column_name' on the Pivot model.

**Comment by ZuggieTM** [comment]
I'm viewing from a Feed resource that is MorphedByMany CustomFeedElemenets.

I did a quick test on the indexQuery function inside HasSortableRows and got the following.

Inside a Feed resource, $query->getQuery()->from returns "custom_feed_elements" and $sortability->model->getTable() returns "feedables" (which is the intermidiate table).

This results in the code never reaching the part where it sorts by "order_column_name".

**Comment by ZuggieTM** [comment]
I think I might have found the issue, but correct me if I'm wrong.

Since we're sorting through a relationship shouldn't we use $request->viaResourceId instead of $request->resourceId inside the if statement ($request->viaManyToMany())?

**Comment by Tarpsvo** [comment]
Hmm, I applied your fix, but I don't have time to test it right now. I'll test and release at latest tomorrow. Did this also fix the issue of sorting controls appearing on both relationship and index views?

**Comment by ZuggieTM** [comment]
Unfortunately not. I don't have time myself to test what causes that. I'll have a look at it either later tonight or tomorrow.

**Comment by ZuggieTM** [comment]
About the sorting controls appearin on both relatinoship and index view, I found the following.

serializeForIndex has "sort_on_index". This is either true of false based on !$sortability->sortOnHasMany && !$sortability->sortOnBelongsTo

Adding "&& $sortability->sortable" to that check fixed it for me. Again, not sure if that breaks sortables that aren't relations, but now you have something to work from at least 👍

**Comment by Tarpsvo** [comment]
Hi! There were many issues under the hood coming from the recent PR-s. I really need to create a project for all these cases to be honest. I only have one with HasMany and a simple ManyToMany relationships.

Anyhow, I made sure they both work right now. Please test the latest version, 1.4.13, and let me know if all looks good on your side. Thanks and good luck!

**Comment by ZuggieTM** [comment]
Thank you 👍

Good luck to you as well :)
