### ISSUE TITLE
Sortable on index AND has many

### ISSUE THREAD

**Issue by JurjenRoels** [optimistdigital/nova-sortable#47]
When putting sort_on_has_many on true. You can no longer sort on the index.

I would like to be able to sort on both index and has many.

When putting sort_on_has_many with the model on true, it disappears from the index.

**Comment by Tarpsvo** [comment]
That's intended. While possible, it's complicated to create two different indexes and keep track of them while sorting them. Nor has this been implemented.

As this package only uses one sort column (by default 'sort_order'), it's not possible to sort on both Index and HasMany as sorting on one of them causes side-effects on the other.

**Comment by JurjenRoels** [comment]
Ah,

Good to know. 

Nice package BTW.

**Comment by pindab0ter** [comment]
I'm using model that can be a parent/child of itself that I group by the parent_id and in the Index I only show root items. If I would like to try to hack the ability to sort both on the index and in the hasMany relationship (assuming the side effects are alleviated by the grouping), where would I start?

**Comment by Tarpsvo** [comment]
> I'm using model that can be a parent/child of itself that I group by the parent_id and in the Index I only show root items. If I would like to try to hack the ability to sort both on the index and in the hasMany relationship (assuming the side effects are alleviated by the grouping), where would I start?

https://github.com/optimistdigital/nova-sortable/issues/60

Here's some info on that.
