### ISSUE TITLE
"class" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by MohmmedAshraf** [optimistdigital/nova-sortable#5]
hey, after installing this package i got this error 
"[Vue warn]: "class" is a reserved attribute and cannot be used as component prop."

![Screen Shot 2019-12-18 at 3 45 52 AM](https://user-images.githubusercontent.com/44909285/71048938-a0a94b00-2149-11ea-901e-d37b60c61edd.png)

**Comment by Tarpsvo** [comment]
Hey!

It didn't raise an error for my version of Vue for some reason. I refactored the code a bit to not use `:class` as a custom prop.

Released a fix in version 1.1.3, try it out! Thanks.

**Comment by MohmmedAshraf** [comment]
Hey, the problem fixed but i got another one after update am using latest version of Nova, 

exactly after done sorting it show this error

> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "resources"

![Screen Shot 2019-12-18 at 4 35 18 PM](https://user-images.githubusercontent.com/44909285/71094884-64f79b00-21b4-11ea-86ae-5d6cee1297ae.png)

**Comment by Tarpsvo** [comment]
Not a clue what's going on to be honest. I'm not mutating resources anywhere as far as I can tell. How come you're getting these errors though and noone else is?

**Comment by MohmmedAshraf** [comment]
I have no idea am just using Nova latest version, Vue version 2.6.11
