### ISSUE TITLE
Unsortable rows

### ISSUE THREAD

**Issue by TheSETJ** [optimistdigital/nova-sortable#51]
In my project, I have rows that I want them to be unsortable. Currently, I'm using something like this to prevent sorting:

```php
// MyModel.php

protected static function boot()
{
    parent::boot();

    static::updating(function ($model) {
        $isSortable = /* some logic */;

        if ($model->isDirty('order_column') && !$isSortable) {
            throw new Exception('Model is not sortable!');
        }
    });
}
```

It works, but it displays 2 error toast on the page, one says "Model is not sortable!" (mine) and the other one says "An error occurred while trying to reorder the resource." (yours). It would be nice if somehow I can define for the package to when accept sorting and when do not.

**Comment by shaffe-fr** [comment]
Hi @TheSETJ, you can try to fail the updates silently:
```php
protected static function boot()
{
    parent::boot();

    static::updating(function ($model) {
        $isSortable = /* some logic */;

        if ($model->isDirty('order_column') && ! $isSortable) {
            return false;
        }
    });
}
```

**Comment by TheSETJ** [comment]
> Hi @TheSETJ, you can try to fail the updates silently:
> 
> ```
> protected static function boot()
> {
>     parent::boot();
> 
>     static::updating(function ($model) {
>         $isSortable = /* some logic */;
> 
>         if ($model->isDirty('order_column') && ! $isSortable) {
>             return false;
>         }
>     });
> }
> ```

This may solve the double error message issue, but I lose my custom error.

**Comment by shaffe-fr** [comment]
Yeah, I guess some tweaks must be done on the frontend side :/

**Comment by Tarpsvo** [comment]
Hi! Version 2.1.0 now allows the user to disable sorting of some rows through `static canSort($request, $resource)`. Check the README for more information. Thanks and good luck!
