### ISSUE TITLE
Sorting on ManyToMany and Index view is possible

### ISSUE THREAD

**Issue by Naoray** [optimistdigital/nova-sortable#60]
The documentation states that

> NB! The resource can only be sorted on either the Index view or the HasMany list view, but not both!

That's not entirely true. If you name the column name on the `PivotModel` different than on your `Model` where you want to sort in the index view (e.g. PivotModel column name: `sort_order`, Model column name: `order_column`) and then add the following method to your Nova Resource

```php
public static function getSortability(NovaRequest $request)
    {
        $response = HasSortableManyToManyRows::getSortability($request);

        if (!$request->viaManyToMany()) {
            return (object)[
                'model' => $response->model,
                'sortable' => $response->sortable,
                'sortOnBelongsTo' => false,
                'sortOnHasMany' => $response->sortOnHasMany,
            ];
        }

        return $response;
    }
```

Don't forget to change the `order_column_name` on your Model to `order_column`.

**Comment by Tarpsvo** [comment]
Yeah, it's possible when using multiple order columns. But providing that out of the box and documenting it so that people actually understand it is quite a challenge. ;)

**Comment by Naoray** [comment]
@Tarpsvo alright. I thought I just let you know in case you didn't. Maybe you can just link to this issue from the documentation somehow, so other ppl encountering this do have a clue on where to start with this.

**Comment by Tarpsvo** [comment]
Added a reference to this issue in the docs. :) Thanks!

**Comment by nammet** [comment]
The getSortability method above will cause the global search to break.  I've solved that by adding an additional check:

`    public static function getSortability($request)
    {
        $response = HasSortableManyToManyRows::getSortability($request);

        if (is_null($response)) {
            return (object)['canSort' => false];
        }

        if (!$request->viaManyToMany()) {
            return (object)[
                'model' => $response->model,
                'sortable' => $response->sortable,
                'sortOnBelongsTo' => false,
                'sortOnHasMany' => $response->sortOnHasMany,
            ];
        }

        return $response;
    }   `
