### ISSUE TITLE
determineOrderColumnName is not callable as it's protected in the SortableTrait

### ISSUE THREAD

**Issue by santilorenzo** [optimistdigital/nova-sortable#62]
The 
`http://my-laravel-server/nova-api/my-model?search=&filters=W10%3D&orderBy=&perPage=25&trashed=&page=1&relationshipType=`
 endpoint returns the following error:
`message: "Call to undefined method App\MyModel::determineOrderColumnName()"`

Unluckily, determineOrderColumnName is defined as protected in the trait, so it can't be called outside the object.
I had to do this dirty trick to make it work:

```
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;

class MyModel extends Model implements Sortable
{
    use SortableTrait {
        determineOrderColumnName as traitDetermineOrderColumnName;
    }

    protected $fillable = ['name', 'order_number'];

    public $sortable = [
        'order_column_name' => 'order_number',
        'sort_when_creating' => true,
      ];

    /**
     * Dirty trick to make HasSortableRows work
     */
    public function determineOrderColumnName() {
        return $this->traitDetermineOrderColumnName();
    }
}
```

Is there a less dirty way to make it work?

**Comment by Tarpsvo** [comment]
Uuuh, doesn't look like it's protected?

https://github.com/spatie/eloquent-sortable/blob/master/src/SortableTrait.php

All functions are public. I think there's something else going on with your project.

**Comment by mineait** [comment]
Just confirming I experience the same issue as OP @santilorenzo .
In the vendor map, this function is protected.

**Comment by santilorenzo** [comment]
@Tarpsvo For some reason nova-sortable requires eloquent-sortable **v3.8.2**. 
From my composer.lock:

```
{
 "name": "optimistdigital/nova-sortable",
 "version": "1.6.1",
 ...
 "require": {
   "laravel/nova": "^2.0.11 || ^3.0",
   "php": ">=7.1.0",
   "spatie/eloquent-sortable": "^3.7.0"
 }
},
...
{
 "name": "spatie/eloquent-sortable",
 "version": "3.8.2",
 ...
}
```

In v3.8.2 of eloquent-sortable that method is protected.
`composer update` didn't help

**Comment by Tarpsvo** [comment]
Hmm, I released version 1.6.2 where the required version is now 3.9. This should do it.

**Comment by santilorenzo** [comment]
Bear in mind that version 3.9 requires php 7.3 and it is no longer compatible with php 7.2.
I'm using php 7.2 now and composer doesn't allow me to update nova-sortable to 1.6.2.

**Comment by Tarpsvo** [comment]
:( It seems it's time to get with the times. I adjusted `nova-sortable` requirements accordingly - PHP 7.3 and Nova 3 (Laravel 7+) minimum now.
