### ISSUE TITLE
All ressources are sortable by default !

### ISSUE THREAD

**Issue by Gil-1** [optimistdigital/nova-sortable#70]
When adding sortable in a projet all Nova Resources are populated by default even without any trait implementation.

This was tested on multiple projects using Nova 3.19.1

**Comment by Tarpsvo** [comment]
Oops, sorry about that! Fixed in version 2.1.1. Thank you for reporting this! :)

**Comment by Gil-1** [comment]
Oohh nice. Thanks for fixing this so quickly :)
