### ISSUE TITLE
Extra tr>td displayed on index view of resources with no actions

### ISSUE THREAD

**Issue by jkudish** [optimistdigital/nova-sortable#73]
Originally reported as a Laravel Nova issue (https://github.com/laravel/nova-issues/issues/3179) but I've narrowed it down to an issue with this package. 

The first tbody>tr>td on the index view is reserved for checkboxes, but for resources that don't have any actions it shouldn't display any. It seems that this package's override of the `ResourceTable` component doesn't account for that and I end up with an extra column and everything is "shifted" over by a column. This happens even on resources which don't declare any sortable traits or columns.

Here's an example:

![image](https://user-images.githubusercontent.com/260253/105412132-26b78100-5be9-11eb-8fe7-86fa3e54bbb3.png)

Disabling/removing this package solves the issue. Can you look into it please?

**Comment by Tarpsvo** [comment]
Scheiße, I thought I handled it. I'll look into it.

**Comment by Tarpsvo** [comment]
Hey @jkudish! I think I managed to find the issue. Please try out version 2.1.5 and let me know. Thanks!

**Comment by jkudish** [comment]
Yes 2.1.5 fixed it 😃
