### ISSUE TITLE
The sort comp doesn't work with delete policy as false

### ISSUE THREAD

**Issue by gustavonecore** [optimistdigital/nova-sortable#75]
I just added the package to my project and worked pretty good!
![image](https://user-images.githubusercontent.com/6432827/107084313-a5a9dd80-67d5-11eb-9769-9d9ed358feb5.png)

**But then, I added a policy to my resource like:**

```php
    public function delete(User $user, ProductCollection $collection)
    {
        return false;
    }
```

And the comp is not available anymore (also the header columns are broken with the related row columns)
![image](https://user-images.githubusercontent.com/6432827/107084402-c40fd900-67d5-11eb-9b83-77c51b5766c9.png)

Can I bypass this issue with another option/setting?

**Comment by Tarpsvo** [comment]
Hey @gustavonecore! There was indeed a bug with this. I fixed it in version 2.1.6. Check it out and let me know if it acts as intended now. Thank you for reporting this and good luck! :)
