### ISSUE TITLE
only_show_on not working for one_to_many relationships

### ISSUE THREAD

**Issue by Jnewbon** [optimistdigital/nova-sortable#76]
The pull request  #36 has the `only_sort_on`, work for both many to many and one to many relationships

The commit 0429ee86ddccbdf16d9c9a649e3b34123a07c3cf changed this para-dime to only allow the `only_sort_on` and `dont_sort_on` to work with many to many relationships and and disables the feature for one-to-many relationships.

Normally one-to-many relationship would only sort on the specific model they relate to but my use case is a nested one to many

**Comic** has-many **Chapters**
**Comic** has-many **Pages**
**Chapter** has-many **Pages**

Inverse

**Page** Belongs-to one **Chapter**
**Page** Belongs-to one **Comic**
**Chapter** Belongs-to one **Comic**

**Comic** <- **Chapter** <- **Page**

Chapters and pages can be sorted, Chapters should only be sorted when viewed under a comic, and pages should only be sorted when viewed under a chapter.

Adding the has sortableTrait to both chapters and pages, makes them sortable, however pages which should only be sortable under chapters is also sortable under comics, which breaks the ordering should the sorting be edited there. 

The following lines
https://github.com/optimistdigital/nova-sortable/blob/58167609b9a35eba40e7a4f4f42b2eb50eda0354/src/Traits/HasSortableRows.php#L52-L70

Need to be placed outside the if statement on line 
https://github.com/optimistdigital/nova-sortable/blob/58167609b9a35eba40e7a4f4f42b2eb50eda0354/src/Traits/HasSortableRows.php#L36

So that they also execute on all relationships not just many to many relationships.

**Comment by Tarpsvo** [comment]
Hey @Jnewbon! Thanks a lot for the very thorough report! As I dug into it, there were many issues I uncovered. I fixed the issue you reported and many more in version 2.1.6. I tested it on both ManyToMany and HasMany relationships and it seemed to work as described now. Please do test out version 2.1.6 and let me know if it anything is still broken. Thank you and good luck! :)
