### ISSUE TITLE
Missing Sort-Buttons since 2.1.6

### ISSUE THREAD

**Issue by cord** [optimistdigital/nova-sortable#79]
We use this package extensively for both sorting resources (`sort_on_index`) but also relations ( `sort_on_has_many` / `sort_on_belongs_to`).

In our use case, we allow to sort a resource (e.g. post) but also the relations to this resource (e.g. user->post) through the pivot table. Prior to 2.1.6 this worked, but now either `sort_on_index` OR `sort_on_belongs_to` is possible.

Would be great if you could re-enable this feature.

Note:
We had some issues to make both sort on index and sort on belongs to work, as the Nova frontend did not show the correct sorting, but the Eloquent relationship worked correctly. 
Nova does not distinguish between table names. So both `users.sort_order` and `post_user.sort_order` are mapped to the same field name `sort_order` within the Nova frontend.
Using a different column name on the pivot table (e.g. `pivot_sort_order`) solved this issue.

@marispro  please add if I missed something

**Comment by Tarpsvo** [comment]
Hi @cord

I added support for Index & BelongsTo simultaneous sorting in 2.1.7. It should start working without any configuration changes.

As for the sort order columns from the main model and pivot clashing, I'm not sure how that happens and will need to investigate further.

Please test 2.1.7 and see if your sorting has returned to how it was. Thanks!

**Comment by marispro** [comment]
@Tarpsvo Hi, we have tested 2.1.7, but unfortunately buttons are still missing.
But on 2.1.5 it works correct.

**Comment by Tarpsvo** [comment]
Hmm, okay. Do you have the spatie/eloquent-sortable's SortableTrait on both the Pivot and the Model you're sorting?

My test project has the following setup:
Artist - ArtistTrack (many-to-many w/ pivot) - Track

Artist resource:
```
class Artist extends Resource
{
    use HasSortableManyToManyRows;
    ...
```

Artist model:
```
class Artist extends Model implements Sortable
{
    use SortableTrait;

    public $sortable = [
        'order_column_name' => 'sort_order',
        'sort_when_creating' => true,
    ];
```

ArtistTrack pivot model:
```
class ArtistTrack extends Pivot implements Sortable
{
    use SortableTrait;

    public $primaryKey = 'id';
    public $incrementing = true;
    public $timestamps = false;

    public $sortable = [
        'order_column_name' => 'pivot_sort_order',
        'sort_when_creating' => true,
    ];
```

And I can sort Artists on both: in Artist resource index view and when viewing the BelongsToMany field on Track.

I'm not sure where else to look at this point, hoping for some more input. :D

**Comment by cord** [comment]
@Tarpsvo thanks a lot for your example, now the sorting works again!

**Comment by Tarpsvo** [comment]
Great to hear! Good luck!
