### ISSUE TITLE
Can you add support to sort for hasMany relation 

### ISSUE THREAD

**Issue by ibraheem9** [optimistdigital/nova-sortable#8]
Can you add support to sort for hasMany relation : 
for example user hasMany posts 
i need to sort user posts

**Comment by Equruler** [comment]
+1

**Comment by albalooshi** [comment]
+1

**Comment by nilsE** [comment]
+1

**Comment by Tarpsvo** [comment]
Hey guys! HasMany sorting has been added in version 1.4.0, though it comes with one drawback: you can only sort on either the Index view OR the HasMany view, but not both. Both would be too difficult to implement at this point. Let me know if this works for you. Good luck!
