### ISSUE TITLE
Sortable should not show inside Lenses

### ISSUE THREAD

**Issue by CosmicodeStudio** [optimistdigital/nova-sortable#80]
I'm having a problem where I have a Lens inside a Resource with HasSortableRows trait, but inside the Lens even with a different order, it shows the order field where I can change the order. I already tried with canSort, but I can't find there if my request it's inside a Lens.

Thank you

**Comment by Tarpsvo** [comment]
Hi! Thanks for reporting this. I fixed it in version 2.1.7, sorting buttons no longer show inside Lenses. Good luck!

**Comment by CosmicodeStudio** [comment]
Thanks so much for your fix!
