### ISSUE TITLE
Option to display sort buttons even if policy denies

### ISSUE THREAD

**Issue by plakhin** [optimistdigital/nova-sortable#83]
I have a model which is denied to be updated by policy, but I still want to be able to sort records.
How can I make sort buttons being displayed in this case?

**Comment by KasparRosin** [comment]
You can check if your sort column is dirty and if it is, you allow sorting.
```php
if ($model->isDirty('sort_order')) {
    if (count($$model->getDirty()) === 1) {
        // Allow updating
    }
}
```

**Comment by plakhin** [comment]
> You can check if your sort column is dirty and if it is, you allow updating.
> 
> ```
> if ($model->isDirty('sort_order') && count($model->getDirty()) === 1 ) {
>     // Allow updating
> }
> ```

Thanks for the answer, but I didn't understand. Where can I do this check?

**Comment by plakhin** [comment]
@KasparRosin if you mean `update()` method of `Policy`, this doesn't help.

What I mean is that I want to hide `Edit` button, but allow sorting.

And I think it makes sense to check update Policy of "parent" model in case `'sort_on_has_many' => true,` because in that case despite the fact we are technically updating the `model` itself (we are updating `sort_order` column of the model), from the perspective of the user we are updating list contents of the "parent" model that hasMany `models`.

**Comment by plakhin** [comment]
Any updates?

**Comment by Tarpsvo** [comment]
Hi @plakhin!

I added a new option to the $sortable array in version 2.2.0. This should fix the case for you. :)

```
class SomeModel extends Eloquent implements Sortable
{
  use SortableTrait;

  public $sortable = [
    'order_column_name' => 'sort_order',
    'sort_when_creating' => true,
    'ignore_policies' => true, // This one
  ];

  ...
}
```

**Comment by plakhin** [comment]
@Tarpsvo 
Thank you for implementing and for the update!
