### ISSUE TITLE
Sort_order has duplicate sort values on update

### ISSUE THREAD

**Issue by GewoonRoy** [optimistdigital/nova-sortable#89]
Maybe i'm doing something wrong but i don't get it to work. 

| Package | Version |
|---|---|
| PHP | 7.4 |
| laravel/nova | 3.22.0 |
| optimistdigital/nova-sortable | 2.2.0 |

I've followed the "Installation" and "Usage" steps completely and added the sortable configuration to the Eloquent model:

```
public $sortable = [
  'order_column_name' => 'sort_order',
  'sort_when_creating' => true,
  'sort_on_has_many' => true,
];
```
In the Nova resource i've added the `use HasSortableRows;` trait. And i've update sort_order field in the table. So i'm starting with the following values in the table:
<img width="109" alt="Schermafbeelding 2021-04-07 om 09 26 13" src="https://user-images.githubusercontent.com/9586175/113827297-6ec75800-9783-11eb-844e-0f45dee58ffc.png">

Now i'm moving the 3rd row to the 2nd row. It does as expected and i get the following result in the table:
<img width="109" alt="Schermafbeelding 2021-04-07 om 09 28 01" src="https://user-images.githubusercontent.com/9586175/113827474-a2a27d80-9783-11eb-863b-cfce5f3523a1.png">

Now I'm moving the 4th row to the 3rd row and it gets a sort_order value which already exists:
<img width="107" alt="Schermafbeelding 2021-04-07 om 09 29 18" src="https://user-images.githubusercontent.com/9586175/113827623-ccf43b00-9783-11eb-91d1-420a14f38176.png">

Am i missing something or is something going wrong in the `fixSortOrder` of the `SortableController`?

**Comment by Tarpsvo** [comment]
Hi! What's your whole setup? Ie relationships (I see you're using it on HasMany). I tried replicating your steps exactly, but wasn't able to reproduce that problem. I tried both HasMany and Index methods.

**Comment by GewoonRoy** [comment]
I tried a different setup and it worked as expected. 🤔 I think i need to research it further on my part. As far as I know the package seems to be working fine. I will open this issue when i might find something which is related to this package. Thank you for the reproduction steps and response, appreciated!
