### ISSUE TITLE
Sort controls not showing in relation tables since version 1.2.0

### ISSUE THREAD

**Issue by ludgerey** [optimistdigital/nova-sortable#9]
**Before Update**

laravel/framework v6.9.0
laravel/nova v2.9.2
optimistdigital/nova-sortable 1.1.3

<img width="1277" alt="Bildschirmfoto 2020-02-18 um 18 48 02" src="https://user-images.githubusercontent.com/1951647/74763145-87bf3200-527f-11ea-9967-caa322adc7df.png">

**After Update**

laravel/framework v6.15.1
laravel/nova v2.10.1
optimistdigital/nova-sortable 1.2.0

<img width="1273" alt="Bildschirmfoto 2020-02-18 um 18 49 37" src="https://user-images.githubusercontent.com/1951647/74763324-e1276100-527f-11ea-9cd6-a17c098550f5.png">

Sorting controls are not shown in detail pages anymore. Before the update there were sorting controls (see the slight difference in the screenshots above).

However in grid views sort controls work as expected. But in my case there I really need them in the detail views as the records are group sorted.

Is this functionality coming back? Is this a bug? Are there workarounds?

**Comment by Tarpsvo** [comment]
I hid them intentionally as they didn't work as intended. I'll bring them back in a release tomorrow and write documentation on how to get them to work properly. Sorry!

**Comment by Tarpsvo** [comment]
I added BelongsToMany support in version 1.3.0. What kind of relationship does your form use? Also, you mentioned that it works on "grid views", what view did you mean by that? The regular index view?

**Comment by ludgerey** [comment]
> What kind of relationship does your form use?

I use a `HasMany` relation.

> The regular index view?

Yes.

**Comment by Tarpsvo** [comment]
Did you get sorting to work as expected on the HasMany relationship?

**Comment by ludgerey** [comment]
Nop. Controls are not showing up.

**Comment by Tarpsvo** [comment]
But before the controls disappeared, did the sorting work?

**Comment by ludgerey** [comment]
Yes. I didn't notice any problems.

**Comment by MilesWuCode** [comment]
my cast

relation : hasMany

A hasMany B

// b model
    public $sortable = [
        'order_column_name' => 'order_column',
        'sort_when_creating' => true,
        // 'sort_on_pivot' => true,
    ];

    public function buildSortQuery()
    {
        return static::query()->where('a_id', $this->a_id);
    }


B not show Sort-UI and not sorting

if  sort_on_pivot => true,

B  show Sort-UI and not save sorting

**Comment by Tarpsvo** [comment]
Still working on HasMany sorting, will try to make a tutorial and compatibility shortly.

**Comment by sashalenz** [comment]
the same trouble, after upgrading to nova 2.11.1

**Comment by mdavis1982** [comment]
@Tarpsvo Is there any update on this at all? I need to get `HasMany` sorting working but the UI isn't showing up.

Thanks 😄

**Comment by Anticom** [comment]
I need this as well. If I can help out by providing a PR etc. let me know.

**Comment by Tarpsvo** [comment]
Hey guys! HasMany sorting has been added in version 1.4.0, though it comes with one drawback: you can only sort on either the Index view OR the HasMany view, but not both. Both would be too difficult to implement at this point. Let me know if this works for you. Good luck!
