### ISSUE TITLE
Allow sorting within relationships

### ISSUE THREAD

**Issue by andrewtweber** [optimistdigital/nova-sortable#91]
Feature request:

If you have a `Poll` model with a hasMany `PollOption`, for example.

I believe you can only sort when viewing the index of the `PollOption` resource type. When viewing an individual Poll, with its PollOptions listed below, unfortunately they are not sortable.

The index listing sorting doesn't really matter to me, because I only care how PollOptions are sorted in relation to others with the same Poll ID.

**Comment by Tarpsvo** [comment]
HasMany docs:
https://github.com/optimistdigital/nova-sortable#sorting-on-hasmany-relationship

ManyToMany docs:
https://github.com/optimistdigital/nova-sortable#sorting-on-manytomany-relationships
