### ISSUE TITLE
The computed property "reorderDisabled" is already defined as a prop.

### ISSUE THREAD

**Issue by vanderb** [optimistdigital/nova-sortable#95]
Hi,
got that error on every resources-table.

`The computed property "reorderDisabled" is already defined as a prop.`

The problem is caused by the `resources/js/components/ReorderButtons.vue` because "reorderDisabled" is both property and computed property.

You can not provide same name for property and computed so you have to rename one of them to fix that error.

Thank you.

**Comment by Tarpsvo** [comment]
Hi! Thanks a lot for reporting this! It should be fixed in version 2.3.4. :)
